name: first workflow
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a sting
        run: echo "hello world"
      - name: Multipleline commands
        run: |
         node -v
         npm -v
  depends-on:
    runs-on: windows-latest
    needs: [run-shell-command]
    steps:
      - name: echo a sting
        run: Write-Output "hello world from window"
      - name: errorsteps
        run: doesn't exixt