name: parallel-jobs
on: [push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run:  echo "hello world"
  second-job:
      runs-on: macos-latest
      steps: 
        - name: view sw version
          run: sw_vers
  third-job:
      runs-on: windows-latest
      needs: [first-job]
      steps: 
        - name: depends-on
          run: Write-Output "windows heelo world"
        - name: error step
          run: doesnotexits
