name: parallel-jobs
on: [push]
jobs:
  first-test:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run:  echo "hello world"
  second-test:
      runs-on: macos-latest
      steps: 
        - name: view sw version
          run: sw_vers
  third-test:
      runs-on: windows-latest
      needs: [first-test]
      steps: 
        - name: depends-on
          run: Write-Output "windows heelo world"
        - name: error step
          run: doesnotexits  # tehere no connad named doesnotexits so it throw erro
